dependencies:
  - name: ui
    version: "1.0.0"
    repository: "file://../ui"
  - name: post
    version: "1.0.0"
    repository: "file://../post"
  - name: comment
    version: "1.0.0"
    repository: "file://../comment"
  - name: mongodb
    version: 9.2.4
    repository: "file://../mongodb"
