---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-pvc-static
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: reddit-mongo-disk
