---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: post
    labels:
      app: reddit
      component: post
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: reddit
        component: post
    template:
      metadata:
        name: post
        labels:
          app: reddit
          component: post
      spec:
        containers:
        - image: alexbee732/post:logging
          name: post
          env:
            - name: POST_DATABASE_HOST
              value: post-db
