version: '3.3'
services:
  post_db:
    image: mongo:${MONGO_VERSION}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - comment_db
  ui:
    build: ./ui
    image: ${USERNAME}/ui:1.0
    ports:
      - ${REDDIT_UI_PORT}:${REDDIT_UI_PORT}/tcp
    networks:
      - front_net
  post:
    build: ./post-py
    image: ${USERNAME}/post:1.0
    networks:
      front_net:
        aliases:
          - post
      back_net:
        aliases:
          - post
  comment:
    build: ./comment
    image: ${USERNAME}/comment:1.0
    networks:
      front_net:
        aliases:
          - comment
      back_net:
        aliases:
          - comment

volumes:
  post_db:

networks:
  front_net:
    driver: bridge
  back_net:
    driver: bridge
